- packages/scrabble-solver/src/components/NavButtons/NavButtons.module.scss
- packages/scrabble-solver/src/components/NavButtons/NavButtons.tsx
- packages/scrabble-solver/src/components/NavButtons/index.ts
- packages/scrabble-solver/src/components/index.ts
- packages/scrabble-solver/src/pages/index.module.scss
- packages/scrabble-solver/src/pages/index.tsx
Closes https://github.com/kamilmielnik/scrabble-solver/issues/26
> Organize buttons

- packages/scrabble-solver/src/components/Board/components/Cell/Button.tsx
- packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
- packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
- packages/scrabble-solver/src/i18n/en.json
- packages/scrabble-solver/src/i18n/pl.json
Closes https://github.com/kamilmielnik/scrabble-solver/issues/27
> Floating icon to toggle blank

- packages/constants/src/index.ts
- packages/models/src/Board.ts
- packages/scrabble-solver/src/api/getServerLoggingData.ts
- packages/scrabble-solver/src/api/index.ts
- packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
- packages/scrabble-solver/src/pages/api/solve.ts
- packages/scrabble-solver/src/pages/api/visit.ts
- packages/scrabble-solver/src/pages/index.tsx
- packages/scrabble-solver/src/sdk/index.ts
- packages/scrabble-solver/src/sdk/visit.ts
- packages/scrabble-solver/src/state/actions.ts
- packages/scrabble-solver/src/state/index.ts
- packages/scrabble-solver/src/state/sagas.ts
- packages/scrabble-solver/src/types/index.ts
Closes https://github.com/kamilmielnik/scrabble-solver/issues/18
> Add more logging

- packages/scrabble-solver/src/components/Radio/Radio.module.scss
Fixes https://github.com/kamilmielnik/scrabble-solver/issues/30
> Clicking inside an icon of non-first unchecked radio button does not select that option

- packages/scrabble-solver/src/components/Splash/Splash.tsx
- packages/scrabble-solver/src/pages/index.tsx
Fixes https://github.com/kamilmielnik/scrabble-solver/issues/31
> Settings sidebar can be seen above the splash on first visit and page refresh

- packages/models/src/Config.ts
- packages/scrabble-solver/src/components/Button/Button.module.scss
- packages/scrabble-solver/src/pages/api/solve.ts
Fixes https://github.com/kamilmielnik/scrabble-solver/issues/32
> Validate max number of blanks passed in tiles in API

- packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
- packages/scrabble-solver/src/components/Results/SolveButton.tsx
- packages/scrabble-solver/src/components/Tiles/Tiles.tsx
- packages/scrabble-solver/src/i18n/pl.json
- packages/scrabble-solver/src/pages/api/solve.ts
- packages/scrabble-solver/src/pages/index.tsx
Closes https://github.com/kamilmielnik/scrabble-solver/issues/41
> Board & titles should be in <form>

- packages/scrabble-solver/src/components/PlainTiles/PlainTiles.module.scss
- packages/scrabble-solver/src/components/Screen/Screen.module.scss
- packages/scrabble-solver/src/components/Screen/Screen.tsx
- packages/scrabble-solver/src/components/Splash/Splash.module.scss
- packages/scrabble-solver/src/components/Splash/Splash.tsx
- packages/scrabble-solver/src/components/Tile/Tile.tsx
- packages/scrabble-solver/src/components/Well/Well.tsx
- packages/scrabble-solver/src/pages/index.tsx
- packages/scrabble-solver/src/styles/animations.scss
Fixes https://github.com/kamilmielnik/scrabble-solver/issues/15
> Board does not shrink when viewport shrinks

- package-lock.json
- packages/configs/src/configs.ts
- packages/configs/src/getConfig.ts
- packages/configs/src/getLocaleConfig.ts
- packages/configs/src/index.ts
- packages/configs/src/isConfigId.ts
- packages/configs/src/literaki.ts
- packages/configs/src/scrabble.ts
- packages/scrabble-solver/src/api/readLocaleDictionary.ts
- packages/scrabble-solver/src/api/validateConfigId.ts
- packages/scrabble-solver/src/api/validateLocale.ts
- packages/scrabble-solver/src/components/Settings/components/ConfigSetting/types.ts
- packages/scrabble-solver/src/components/Settings/components/LocaleSetting/LocaleSetting.tsx
- packages/scrabble-solver/src/components/Settings/components/LocaleSetting/options.ts
- packages/scrabble-solver/src/components/Settings/components/LocaleSetting/types.ts
- packages/scrabble-solver/src/i18n/index.ts
- packages/scrabble-solver/src/lib/detectLocale.ts
- packages/scrabble-solver/src/lib/isLocale.ts
- packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
- packages/scrabble-solver/src/pages/api/solve.ts
- packages/scrabble-solver/src/sdk/findWordDefinition.ts
- packages/scrabble-solver/src/sdk/solve.ts
- packages/scrabble-solver/src/state/localStorage.ts
- packages/scrabble-solver/src/state/slices/settingsInitialState.ts
- packages/scrabble-solver/src/state/slices/settingsSlice.ts
- packages/scrabble-solver/src/types/index.ts
- packages/types/src/Locale.ts
- packages/types/src/index.ts
Closes https://github.com/kamilmielnik/scrabble-solver/issues/53
> Refactor "Locale" type to an enum

- packages/scrabble-solver/src/api/normalizeDefinition.ts
- packages/scrabble-solver/src/api/translateEn.ts
- packages/scrabble-solver/src/api/translateFr.ts
- packages/scrabble-solver/src/api/translatePl.ts
- packages/scrabble-solver/src/i18n/fr.json
Closes https://github.com/kamilmielnik/scrabble-solver/issues/52
> Implement "/dictionary" endpoint for French

- packages/scrabble-solver/src/components/Screen/Screen.tsx
- packages/scrabble-solver/src/components/Splash/Splash.module.scss
- packages/scrabble-solver/src/components/Splash/Splash.tsx
- packages/scrabble-solver/src/pages/index.tsx
Fixes https://github.com/kamilmielnik/scrabble-solver/issues/63
> Issues with splash animation

- .github/workflows/build.yml
- README.md
Closes https://github.com/kamilmielnik/scrabble-solver/issues/67
> Add "build" GitHub action

- packages/configs/README.md
- packages/constants/README.md
- packages/dictionaries/README.md
- packages/logger/README.md
- packages/scrabble-solver/README.md
- packages/solver/README.md
- packages/types/README.md
- packages/word-definitions/README.md
- packages/word-lists/README.md
Closes https://github.com/kamilmielnik/scrabble-solver/issues/78
> Add README with package description to every package

- packages/scrabble-solver/src/components/NotFound/NotFound.module.scss
- packages/scrabble-solver/src/components/NotFound/NotFound.tsx
- packages/scrabble-solver/src/components/NotFound/index.ts
- packages/scrabble-solver/src/components/index.ts
- packages/scrabble-solver/src/icons/dashCircleFill.svg
- packages/scrabble-solver/src/icons/index.ts
- packages/scrabble-solver/src/pages/404.tsx
Closes https://github.com/kamilmielnik/scrabble-solver/issues/81
> Custom 404 page

- packages/dictionaries/package.json
- packages/dictionaries/src/Dictionaries.ts
- packages/dictionaries/src/lib/downloadDictionary.ts
Closes https://github.com/kamilmielnik/scrabble-solver/issues/75
> Add logging to @scrabble-solver/dictionaries

- packages/scrabble-solver/src/components/Board/Board.tsx
- packages/scrabble-solver/src/components/Board/BoardPure.tsx
- packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
- packages/scrabble-solver/src/components/Board/components/Cell/Cell.tsx
- packages/scrabble-solver/src/components/Board/components/Cell/CellPure.tsx
- packages/scrabble-solver/src/components/Board/hooks/useGrid.ts
- packages/scrabble-solver/src/components/Board/lib/getPositionInGrid.ts
- packages/scrabble-solver/src/components/Board/lib/index.ts
- packages/scrabble-solver/src/components/Board/types/index.ts
- packages/scrabble-solver/src/styles/mixins.scss
Closes https://github.com/kamilmielnik/scrabble-solver/issues/80
> Use single keydown event handler for board navigation

- packages/scrabble-solver/package-lock.json
- packages/scrabble-solver/package.json
- packages/scrabble-solver/src/components/KeyMap/KeyMap.tsx
- packages/scrabble-solver/src/components/NavButtons/NavButtons.module.scss
- packages/scrabble-solver/src/components/RemainingTiles/RemainingTiles.tsx
- packages/scrabble-solver/src/components/Settings/Settings.tsx
- packages/scrabble-solver/src/components/Sidebar/Sidebar.module.scss
- packages/scrabble-solver/src/components/Sidebar/Sidebar.tsx
- packages/scrabble-solver/src/components/Tile/Tile.module.scss
- packages/scrabble-solver/src/pages/index.tsx
- packages/scrabble-solver/src/parameters/index.ts
Closes https://github.com/kamilmielnik/scrabble-solver/issues/87
> Use react-modal in Sidebar

- README.md
- packages/scrabble-solver/src/i18n/en.json
- packages/scrabble-solver/src/i18n/fr.json
- packages/scrabble-solver/src/i18n/pl.json
Closes https://github.com/kamilmielnik/scrabble-solver/issues/107
> Remove info about wiktionary

- packages/types/src/CharacterBonus.ts
Hey @kamilmielnik 
thanks a lot for your help and your reactivity with the issue #112. I tried to fix the bug with your indications and it worked.
> fix bug on character bonus tiles

- .gitignore
- packages/configs/src/scrabble/tiles/tilesPl.ts
> fix(configs): update scores of scrabble PL tiles

- packages/scrabble-solver/src/components/Board/Board.module.scss
- packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
Fixes https://github.com/kamilmielnik/scrabble-solver/issues/119
> Fix grid styling regression in webkit

- packages/scrabble-solver/src/components/Results/Result.tsx
> Change result candidate when focused using tab key in results list

- packages/word-lists/package-lock.json
- packages/word-lists/package.json
- packages/word-lists/src/getPlPlWordList.ts
- packages/word-lists/src/lib/downloadFile.ts
- packages/word-lists/src/lib/downloadHtml.ts
Fixes https://github.com/kamilmielnik/scrabble-solver/issues/133
> Polish dictionary URL has changed

- packages/scrabble-solver/src/styles/global.scss
- Closes https://github.com/kamilmielnik/scrabble-solver/issues/130
> Fix horizontal scrollbar shown when animating sidebar

- .eslintrc.js
- packages/scrabble-solver/src/components/Dictionary/Dictionary.tsx
- packages/scrabble-solver/src/components/Results/Results.tsx
- packages/scrabble-solver/src/lib/memoize.ts
- packages/scrabble-solver/src/sdk/fetchJson.ts
- packages/scrabble-solver/src/sdk/findWordDefinitions.ts
- packages/scrabble-solver/src/sdk/solve.ts
- packages/scrabble-solver/src/sdk/verify.ts
- packages/scrabble-solver/src/state/sagas.ts
- packages/scrabble-solver/src/state/selectors.ts
- packages/scrabble-solver/src/state/slices/dictionaryInitialState.ts
- packages/scrabble-solver/src/state/slices/dictionarySlice.ts
- packages/scrabble-solver/src/state/slices/solveInitialState.ts
- packages/scrabble-solver/src/state/slices/solveSlice.ts
- packages/types/src/index.ts
- packages/types/src/isError.ts
Closes https://github.com/kamilmielnik/scrabble-solver/issues/13
> Real error messages in error states

- packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
- packages/scrabble-solver/src/components/Board/hooks/useGrid.ts
- packages/scrabble-solver/src/components/EmptyState/EmptyState.tsx
- packages/scrabble-solver/src/components/Loading/Loading.tsx
- packages/scrabble-solver/src/components/NavButtons/NavButtons.module.scss
- packages/scrabble-solver/src/components/NavButtons/NavButtons.tsx
- packages/scrabble-solver/src/components/Rack/Rack.tsx
- packages/scrabble-solver/src/components/Radio/Radio.module.scss
- packages/scrabble-solver/src/components/Results/Results.module.scss
- packages/scrabble-solver/src/components/Settings/components/LocaleSetting/LocaleSetting.module.scss
- packages/scrabble-solver/src/components/Sidebar/Sidebar.module.scss
- packages/scrabble-solver/src/hooks/index.ts
- packages/scrabble-solver/src/hooks/useDirection.ts
- packages/scrabble-solver/src/hooks/useLanguage.ts
- packages/scrabble-solver/src/i18n/constants.ts
- packages/scrabble-solver/src/pages/index.module.scss
- packages/scrabble-solver/src/pages/index.tsx
- packages/word-definitions/src/lib/normalizeDefinition.ts
Closes https://github.com/kamilmielnik/scrabble-solver/issues/171
> RTL support

- .prettierignore
- packages/scrabble-solver/src/components/Board/components/Cell/Cell.module.scss
- packages/scrabble-solver/src/components/RemainingTiles/Character.module.scss
- packages/scrabble-solver/src/components/RemainingTiles/RemainingTiles.module.scss
- packages/scrabble-solver/src/components/Results/Results.module.scss
- packages/scrabble-solver/src/components/Settings/components/ConfigSetting/ConfigSetting.module.scss
- packages/scrabble-solver/src/components/Settings/components/LocaleSetting/LocaleSetting.module.scss
- packages/scrabble-solver/src/components/Settings/components/LocaleSetting/LocaleSetting.tsx
- packages/scrabble-solver/src/components/SvgFontCss/SvgFontCss.tsx
- packages/scrabble-solver/src/components/Tile/Tile.module.scss
- packages/scrabble-solver/src/components/Words/Words.module.scss
- packages/scrabble-solver/src/styles/global.scss
Closes https://github.com/kamilmielnik/scrabble-solver/issues/172
> Better font for Persian

- packages/scrabble-solver/src/service-worker/average.ts
- packages/scrabble-solver/src/service-worker/routeSolveRequests.ts
Closes https://github.com/kamilmielnik/scrabble-solver/issues/189
> Do not use client-side solver on slow devices

- packages/scrabble-solver/src/components/Board/hooks/useGrid.ts
- packages/scrabble-solver/src/modals/KeyMapModal/KeyMapModal.tsx
Closes https://github.com/kamilmielnik/scrabble-solver/issues/233
> Arrow key to change direction of input

- packages/scrabble-solver/src/components/Board/hooks/useGrid.ts
- packages/scrabble-solver/src/components/Rack/Rack.tsx
- packages/scrabble-solver/src/components/Rack/RackTile.tsx
- packages/scrabble-solver/src/lib/index.ts
- packages/scrabble-solver/src/lib/isCtrl.ts
- packages/scrabble-solver/src/modals/KeyMapModal/KeyMapModal.tsx
Closes https://github.com/kamilmielnik/scrabble-solver/issues/252
> Remove Ctrl+? keyboard shortcuts

- packages/scrabble-solver/src/pages/api/dictionary/[locale]/[word].ts
- packages/scrabble-solver/src/pages/api/dictionary/[locale]/index.ts
- packages/scrabble-solver/src/pages/api/solve.ts
- packages/scrabble-solver/src/pages/api/verify.ts
- packages/scrabble-solver/src/pages/api/visit.ts
Probably fixes https://github.com/kamilmielnik/scrabble-solver/issues/235
> Do not re-throw API errors

- packages/scrabble-solver/src/components/Board/Board.module.scss
- packages/scrabble-solver/src/components/Board/Board.tsx
- packages/scrabble-solver/src/components/Board/BoardPure.tsx
- packages/scrabble-solver/src/components/Board/hooks/useBackgroundImage.tsx
- packages/scrabble-solver/src/components/Board/hooks/useBoardStyle.ts
- packages/scrabble-solver/src/components/Board/lib/getCoordinate.ts
- packages/scrabble-solver/src/components/Board/lib/index.ts
- packages/scrabble-solver/src/components/Results/Results.module.scss
- packages/scrabble-solver/src/hooks/useAppLayout.ts
- packages/scrabble-solver/src/i18n/languages/english.json
- packages/scrabble-solver/src/i18n/languages/french.json
- packages/scrabble-solver/src/i18n/languages/german.json
- packages/scrabble-solver/src/i18n/languages/persian.json
- packages/scrabble-solver/src/i18n/languages/polish.json
- packages/scrabble-solver/src/i18n/languages/romanian.json
- packages/scrabble-solver/src/i18n/languages/spanish.json
- packages/scrabble-solver/src/modals/SettingsModal/SettingsModal.tsx
- packages/scrabble-solver/src/modals/SettingsModal/components/ShowCoordinatesSetting/ShowCoordinatesSetting.module.scss
- packages/scrabble-solver/src/modals/SettingsModal/components/ShowCoordinatesSetting/ShowCoordinatesSetting.tsx
- packages/scrabble-solver/src/modals/SettingsModal/components/ShowCoordinatesSetting/index.ts
- packages/scrabble-solver/src/modals/SettingsModal/components/index.ts
- packages/scrabble-solver/src/parameters/index.ts
- packages/scrabble-solver/src/state/localStorage.ts
- packages/scrabble-solver/src/state/selectors.ts
- packages/scrabble-solver/src/state/slices/settingsInitialState.ts
- packages/scrabble-solver/src/state/slices/settingsSlice.ts
- packages/scrabble-solver/src/state/store.ts
- packages/scrabble-solver/src/types/index.ts
- packages/types/src/ShowCoordinates.ts
- packages/types/src/index.ts
> Display board coordinates

- packages/configs/src/languages/english.ts
- packages/scrabble-solver/src/components/Board/BoardPure.tsx
- packages/scrabble-solver/src/components/Board/components/Actions/Actions.tsx
- packages/scrabble-solver/src/components/Board/hooks/useBackgroundImage.tsx
- packages/scrabble-solver/src/icons/Ban.svg
- packages/scrabble-solver/src/icons/index.ts
- packages/scrabble-solver/src/lib/groupResults.ts
- packages/scrabble-solver/src/lib/index.ts
- packages/scrabble-solver/src/lib/resultMatchesCellFilter.ts
- packages/scrabble-solver/src/state/sagas.ts
- packages/scrabble-solver/src/state/selectors.ts
- packages/scrabble-solver/src/state/slices/cellFilterInitialState.ts
- packages/scrabble-solver/src/state/slices/cellFilterSlice.ts
- packages/scrabble-solver/src/types/index.ts
> Target destination - exclude position
